lib/execution_engine2/execution_engine2Impl.py
lib/execution_engine2/utils/Condor.py

I took the `deploy.cfg` file as the point of truth and converted other references to the "initialdir" field to be in compliance.

fix intialdir and initial_dir -> initialdir as in deploy.cfg

---

execution_engine2.spec

This is just an update to the notes and formatting of the execution_engine2.spec file (for now).
Really, I just wanted to document somewhere other than the code what each field is and what's available. I don't have the list of allowed projection strings yet, but I'm guessing they map onto the class names from `lib/execution_engine2/models/models.py`?
I also want to just throw out a recommendation here to change the returned name of "_id" (which is a mongoism/database-ism) to either "id" or "job_id". I'd prefer "job_id", since that's used throughout the rest of the ee2 API.

Added notes, description to various fields

---

lib/execution_engine2/utils/MongoUtil.py
lib/execution_engine2/utils/SDKMethodRunner.py
test/ee2_SDKMethodRunner_test.py
test/ee2_scheduler_integration_test.py
test/test_utils.py

Works toward #47 , specifically converts _id in the returned job state to "job_id", and adds reasonably exhaustive validation tests to the non-projected job_state structure.

convert _id to job_id in returned job state

---

lib/execution_engine2/SDKMethodRunner.py
lib/execution_engine2/execution_engine2Impl.py
test/deploy.cfg
test/ee2_SDKMethodRunner_test.py
test/ee2_authstrategy_test.py
test/test_utils.py

1. Use the authstrategy commands throughout SDKMethodRunner. This took a little rewriting, but abstracts away most of the Workspace auth commands.
2. Remove the need to pass the whole context object around all the time. Each API call creates a new SDKMethodRunner, so this just passes the necessary information (user id and token) at construction time.
3. Update tests to account for the above. Does more mocking at the http API level instead of mocking out calls so more code gets executed.
Still pending in the next PR - more negative tests, failure checking, and tests against the API (i.e. loading the impl module and testing directly against that).

Use authstrategy throughout SDKMethodRunner

---

lib/execution_engine2/SDKMethodRunner.py
lib/execution_engine2/execution_engine2Impl.py
test/deploy.cfg
test/ee2_SDKMethodRunner_test.py
test/ee2_authstrategy_test.py
test/test_utils.py

Admin access should only be checked when using the administer command, and shouldn't override any other failed permissions. That is, a user who happens to have an admin role shouldn't just be able to run cancel_job on any job - that seems like an easy way to accidentally cancel things.

Admin console issues

---

lib/execution_engine2/utils/Condor.py

Jobs are removed so they do not update ee2
However, if we put them on hold, the hold reaper will capture them and mark them correctly. 
I didn't test it, I just read the documentation

DATAUP-181 Change periodic remove, to periodic hold

---

RELEASE_NOTES.md
bin/PurgeHeldJobs.py

Prevent the job reaper from exiting on error, just continue trying to reap
Didn't write tests for this script.

DataUp-181 Prevent Reaper from quitting

---

lib/execution_engine2/sdk/EE2StatusRange.py
lib/execution_engine2/sdk/SDKMethodRunner.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py

SDKMR allows passing in `None` for the user id and token in the constructor, but there are no cases where this functionality is actually used. Simplify the code by requiring user credentials at initialization.
- [?] My changes generate no new warnings - too many warnings to reasonably tell
- [n/a] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during …

Make token and user id required for sdkmr

---

test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2RunjobBatch_test.py

* actually turns into thread
* adds more handling of failure modes
* adds more testing
* Details for how to test the PR:

Business logic for runjob batch tests 

---

README.md
lib/execution_engine2/constants.py
lib/execution_engine2/execution_engine2Impl.py
lib/execution_engine2/sdk/EE2Authentication.py
lib/execution_engine2/sdk/EE2Constants.py
lib/execution_engine2/sdk/EE2Runjob.py
lib/execution_engine2/sdk/EE2Status.py
lib/execution_engine2/sdk/SDKMethodRunner.py
lib/execution_engine2/utils/APIHelpers.py
lib/execution_engine2/utils/clients.py
test/tests_for_auth/ee2_admin_mode_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_EE2Logs_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Runjob_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Status_test.py
test/tests_for_sdkmr/ee2_load_test.py
test/tests_for_utils/clients_test.py
test/utils_shared/test_utils.py

UCS contains the clients that need to be instantiated on a per user basis.
UCS is passed in to SDKMR to 1) simplify the SDKMR constructor, and 2) allow for eventual unit testing of SDKMR, since the UCS and workspace client can be mocked via create_autospec.
Also add instructions for running pre-commit hooks.
- [?] My changes generate no new warnings - too many warnings to feasibly check

pass a UserClientSet into SDKMethodRunner

---

.flake8
lgtm.yml
lib/biokbase/README.md
lib/biokbase/log.py
lib/execution_engine2/README.md
lib/execution_engine2/authclient.py
pyproject.toml
test/tests_for_integration/api_to_db_test.py
test/utils_shared/test_utils.py

Starts the ee2 service as part of the API to DB tests. Next step is actually adding the is_admin test.
Manually verified that the status() is printed out correctly and that the tests pass in Docker.
To run an API to DB test I need to start the service. The service expects a
couple of files in specific places in the repo, so I had to check them in.
- [n/a] My changes generate no new warnings - 3000+ warnings

Start up ee2 service in api to db test

---

lib/execution_engine2/db/models/models.py
lib/execution_engine2/sdk/EE2Runjob.py
lib/execution_engine2/sdk/SDKMethodRunner.py
lib/execution_engine2/utils/CatalogUtils.py
test/tests_for_sdkmr/EE2Runjob_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py

Fixes a bug where a SDKMR.get_workspace() method was expected but was removed in a
previous PR.
Creates a unit test for the run() method where the bug occurred.
- [?] My changes generate no new warnings - over 3k warnings currently

Fix workspace client access bug & unit test

---

lib/execution_engine2/sdk/EE2StatusRange.py
lib/execution_engine2/sdk/SDKMethodRunner.py
test/tests_for_sdkmr/EE2StatusRange_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py

Also add unit tests.
Previously if the user was None it would be set to the user's name, but
that behavior was [mistakenly removed](https://github.com/kbase/execution_engine2/pull/294/files#diff-6d81ae439caaea9fb9b5db38b7b8c490b9ea5ef32cd59292797bf14fdf5da751L77-R78) when making user_id and token
required fields in SDKMR. Without that behavior, a user = None filter is added to
the mongo query which matches no jobs.
Closes #318.
- [?] My changes generate no new warnings - 3K+ warnings
- [n/a] [Version has been …

Fix date range job search bug

---

lib/execution_engine2/sdk/EE2Status.py
test/tests_for_sdkmr/EE2Status_test.py
test/tests_for_sdkmr/ee2_load_test.py

EE2status attempting to access get_catalog_utils().catalog caused
finish_job() to throw an exception and consequently the job runner to freak out:
kbase/JobRunner#43
Accessed the catalog directly and added a unit test that covers the code
in question.
Also reduced the EE2Status API by making a method that was only used in tests "private".
- [n/a] [Release notes](/RELEASE_NOTES.md) have been updated …

Fix finish_job bug, add tests

---

lib/execution_engine2/utils/CatalogUtils.py
test/tests_for_sdkmr/ee2_scheduler_test.py

Fixes: https://github.com/kbase/execution_engine2/issues/332
In short, the CSV inputs shown in the catalog UI are already split into
separate strings before being sent to the catalog, so the split is not
necessary. Only accepting the first entry in the list causes everything
except the client group to be ignored.
- [n/a] …

Fix bug processing catalog client groups in CSV format

---

RELEASE_NOTES.md

Missed release notes for #333
This repo doesn't seem to bump a version anywhere other than the release notes
- [n/a ] I have commented my code, particularly in hard-to-understand areas

Add release notes for CSV bugfix

---

README.md
lib/execution_engine2/sdk/job_submission_parameters.py
test/deploy.cfg
test/tests_for_sdkmr/job_submission_parameters_test.py

Add a job requirements checker to be used in the job resolver prior to creating the requirements.
Minor changes:
* normalize booleans
* rename `as_user` to `bill_to_user` to clarify what the parameter does
* remove a typo in the test `deploy.cfg` file.
* document EE2 expectations of client group specifications in the catalog service

DATAUP-389: Add a job requirements checker

---

README.md
lib/execution_engine2/utils/job_requirements_resolver.py
test/tests_for_utils/job_requirements_resolver_test.py

First step of adding a class to determine the requirements of a job from 3 sources - user input, the catalog record for the method, and the EE2 configuration file.
This PR adds a method to normalize job requirements given in `dict` format - e.g. parse strings to ints, etc. This is particularly useful for the catalog and config file sources since the former can present as a CSV string and the latter is an ini file, so all values are strings.
Expect 4 total PRs to complete the requirements resolver class.
- [n/a] [Release notes](/RELEASE_NOTES.md) …

DATAUP-389 - add a job requirements resolver, pt 1

---

lib/execution_engine2/utils/job_requirements_resolver.py
test/tests_for_utils/job_requirements_resolver_test.py

Determine a requirements type based on job requirements. This will be used
to determine whether a user is allowed to run a job with non-default
requirements based on their ee2 admin status.
*Probably* for now anything other than standard will require write admin but
billing is split out as billing a job to another user seems like a step above
merely specifying how a job is run.
- [n/a] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of …

DATAUP-389 - add a job requirements resolver, pt 2 of 4

---

lib/execution_engine2/sdk/EE2Constants.py
lib/execution_engine2/utils/job_requirements_resolver.py
test/tests_for_utils/job_requirements_resolver_test.py

Adds the constructor for the job resolver and tests spec parsing for default job requirements values. The next (and last for the resolver module) PR will add the resolution code itself.

DATAUP-389 - add a job requirements resolver, pt 3 of 4

---

lib/execution_engine2/utils/job_requirements_resolver.py
test/tests_for_utils/job_requirements_resolver_test.py

After reviewing the code again, it's clear that any user (who is presumed
to be a catalog admin) provided client group should override every other
source, including the `OVERRIDE_CLIENT_GROUP` environmental variable.

DATAUP-389 - Make the user client group override the override

---

lib/execution_engine2/execution_engine2Impl.py
lib/execution_engine2/utils/clients.py
test/tests_for_auth/ee2_admin_mode_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_EE2Logs_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Runjob_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Status_test.py
test/tests_for_sdkmr/ee2_load_test.py
test/tests_for_utils/clients_test.py
test/utils_shared/mock_utils.py

Adds catalog client and job reqs resolver to the client set.
Nothing does anything with them yet - will be tested more thoroughly when that happens.
Adds a separate field for the catalog client, as the job reqs resolver will make CatalogUtils redundant.

DATAUP-389 - integrate the job requirements resolver pt 1

---

lib/execution_engine2/sdk/EE2Runjob.py
lib/execution_engine2/sdk/EE2Status.py
lib/execution_engine2/sdk/SDKMethodRunner.py
test/tests_for_auth/ee2_admin_mode_test.py
test/tests_for_sdkmr/EE2Runjob_test.py
test/tests_for_sdkmr/EE2Status_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py
test/tests_for_sdkmr/ee2_load_test.py

Adds several getters for clients that were added to the client set in the last PR, and for clients for which getters will be needed for the upcoming integration of the job requirements resolver code in order to mock said clients.
- [? My changes generate no new warnings - 3k+ warnings

DATAUP-389 - add getters for new clients & missing getters

---

lib/execution_engine2/sdk/SDKMethodRunner.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py

Remove the `SDKMR.is_admin` field, which is not actually used anywhere.
Remove a couple of mocked fields on SDKMR that don't actually exist.

DATAUP-389 - remove unused fields

---

lib/execution_engine2/sdk/SDKMethodRunner.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py

Needed for mocking the case where a Job object has the save() method
called on it and is then continued to be used. The save() method has a
side effect of modifying the Job object to add an `.id` field, and so to
mock that the method that calls save() on the job must return the updated job.

DATAUP-389 - Add sdkmr.save_and_return_job

---

test/tests_for_sdkmr/EE2Runjob_test.py

Factors out some mocking that will be in common with other tests once
the job requirements resolution code will be integrated. Should make the
upcoming changes easier to understand.

DATAUP-389 - refactor RunJob unit tests

---

lib/execution_engine2/sdk/job_submission_parameters.py
test/tests_for_sdkmr/job_submission_parameters_test.py

Mypy should really be used for that check, but it turns out this class will be the first thing to encounter s_ws_o, so in the interests of utility sticking the check in there.

DATAUP-389 - check that source_ws_objects is a list

---

lib/execution_engine2/sdk/EE2Runjob.py

Not necessary and allows setting a job's parent to an arbitrary job, which is not what we want. Confirmed with @bio-boris 

DATAUP-389 - don't allow users to set a job's parent job

---

test/tests_for_integration/api_to_db_test.py
test/tests_for_integration/workspace_controller.py
test/tests_for_integration/wsjars

Adds the workspace service to the integration tests for use in future PRs.

DATAUP-389 - Add workspace instance to integration tests

---

test/tests_for_integration/api_to_db_test.py
test/utils_shared/test_utils.py

What it says on the tin. Note that the notes at the top of the `api_to_db_test.py` file are pretty important.

DATAUP-389 - add run_job integration test

---

lib/execution_engine2/sdk/EE2Constants.py
lib/execution_engine2/sdk/EE2Runjob.py
test/tests_for_sdkmr/EE2Runjob_test.py

* When integrating the job requirements resolver, I missed that when a clientgroup is not provided in the call to `run_job_concierge` a default is provided. The default has been added.
* The default concierge client group in `EE2Constants.py` does not match the name of the client group used in production and in the `deploy.cfg` file, so `s/kbase_concierge/concierge/`.

DATAUP-389 - fix a couple of concierge related bugs

---

lib/execution_engine2/execution_engine2Server.py
test/tests_for_integration/api_to_db_test.py

At some point someone introduced a bug into the SDK that causes the python server file to unnecessarily quote error strings. This fixes that locally. 
Added an SDK issue for an eventual `fix`: https://github.com/kbase/kb_sdk/issues/363

DATAUP-389 - fix Server.py quoting error messages

---

lib/execution_engine2/utils/Condor.py
test/deploy.cfg
test/tests_for_integration/api_to_db_test.py

DATAUP-389 - Add happy path integration tests for run_job_concierge

---

test/tests_for_integration/api_to_db_test.py

DATAUP-389 - Add unhappy path integration tests for run_job_concierge

---

build/templates/deploy.docker.cfg.templ

The tests key off `KB_DEPLOYMENT_CONFIG` to find the `deploy.cfg` file,
which in the container points to `/kb/module/deploy.cfg`. It appears that
that file is generated from the template in `build/templates`, which
hadn't been updated with the `concierge` section, so the tests failed.
Note there are 3 different `deploy.cfg` files in the repo, which can make debugging a bit confusing.
- [n/a] Any …

Make test pass in docker container

---

requirements.txt

"The id field is already used to implement the time_span filter, resulting it its usage in a regular field. This prevents the usage of id in a user-provided filter, which is used in a _raw_ filter."

SCT-3026 Upgrade mongo-engine

---

test/tests_for_auth/ee2_admin_mode_test.py
test/tests_for_integration/api_to_db_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Runjob_test.py
test/tests_for_sdkmr/ee2_load_test.py
test/utils_shared/mock_utils.py

What is says on the tin. There's a particular catalog call that accepts any input and returns a reasonable output, so it's easy to miss when mocking.
There's also one test that contacts the external auth service. For now I just added a toggle to manually skip it, but we may want to discuss moving it to the `api_to_db_test` file and using the local auth service started there for the test.
- [n/a] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge …

DATAUP-389 - Make tests pass when CI is down

---

lib/execution_engine2/sdk/EE2Runjob.py
lib/execution_engine2/utils/job_requirements_resolver.py
test/tests_for_integration/api_to_db_test.py
test/tests_for_sdkmr/EE2Runjob_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py

What it says on the tin.
Next steps in a future PR:
- in the Impl.py file, pass in an `as_admin` parameter so it's actually possible to specify job requirements at the API level
- add integration tests

DATAUP-389 - specify job requirements in run_job[_batch]

---

execution_engine2.spec
lib/execution_engine2/db/models/models.py
lib/execution_engine2/sdk/EE2Runjob.py
lib/execution_engine2/sdk/EE2Status.py
lib/execution_engine2/sdk/EE2StatusRange.py
test/tests_for_db/ee2_MongoUtil_test.py
test/tests_for_integration/api_to_db_test.py
test/tests_for_sdkmr/EE2StatusRange_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Runjob_test.py
test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Status_test.py
test/tests_for_sdkmr/ee2_retry_test.py

Summary:
In order to ensure DB consistency, we need to rework the retry mechanism
Remove retry_count field from record
Add retry_ids field to record
Change check_job/check_jobs to return “retry_count” in addition to “retry_ids”
Change retry to return “retry_ids”
Add a toggle field to ensure database is consistent in terms of updating the parent_retry and parent_job_id  
* Deployed on CI
* Delete all records with retries in CI db, and prod db.
```
db.getCollection('ee2_jobs').update({'retry_count' : { $exists: true }}, { $set: {"retry_ids": [] }}, {upsert:false,
multi:true})  
db.getCollection('ee2_jobs').update({'retry_count' : { $exists: true }}, { $unset: {"retry_count" : ""}}, {upsert:false,
multi:true})  
db.getCollection('ee2_jobs').find({'retry_count' : { $exists: true }})
```

DATAUP-461 Refactor Retry

---

lib/execution_engine2/utils/catalog_cache.py
test/tests_for_utils/catalog_cache_test.py

The catalog cache exposes the cache internals by reference when returning job requirements, which means that any modification of the returned value modifies the cache. The job requirements resolver does exactly this for CSV formatted client group info from the catalog, popping the client group from the front of the list. This means that for any given app, the first run works normally and any later runs see an empty requirements set if only the clientgroup is specified, or a corrupted requirements set if there are more key/value pairs after the client group.
This PR prevents alteration of the cache by an external client.
- [n/a] I have made corresponding changes to …

Protect the catalog cache internals from external mutation

---

docs/adrs/004-SplitAndAggregate.md

DATAUP-262 Create ADR For Split/Aggregate Jobs

---

lib/execution_engine2/db/MongoUtil.py
test/tests_for_db/ee2_MongoUtil_test.py

The tests pass with or without the changes in this commit in the docker
container, which is UTC, but fail without the changes on my laptop, which is
not UTC.
The problem is that `datetime.utcnow()` is not timezone aware, so it
only works on UTC systems.

Fix tests on non-UTC systems

---

lib/execution_engine2/db/MongoUtil.py
test/tests_for_db/ee2_MongoUtil_test.py

What's on the tin - add a method that updates a single job to the queued state. Next PR will update EE2RunJob to use it instead of the batched method.

DATAUP-679: Add MongoUtil method to update a single job to queued

---

RELEASE_NOTES.md
kbase.yml
lib/execution_engine2/db/MongoUtil.py
lib/execution_engine2/execution_engine2Impl.py
lib/execution_engine2/sdk/EE2Runjob.py
test/tests_for_db/ee2_MongoUtil_test.py
test/tests_for_sdkmr/EE2Runjob_test.py

If many jobs are submitted in a batch, the jobs can start running before
being updated to queued, which means the jobs never get a queued timestamp.

DATAUP-679: Update job to queued directly after submit 

---

RELEASE_NOTES.md
kbase.yml
lib/execution_engine2/db/MongoUtil.py
lib/execution_engine2/execution_engine2Impl.py
test/tests_for_db/ee2_MongoUtil_test.py
test/tests_for_db/ee2_model_test.py

The current MongoUtil implementation has one `mongo_collection` instance
variable that can be set to either the jobs collection or the logs collection
depending on which method was called last. Methods that don't explicitly
choose the collection themselves will use the collection set by whichever
method was most recently called, which might be the wrong collection.
This commit makes two separate variables and ensures the right
collection is being used for each method. It also deletes a number of
unused methods.
- [?] My changes …

Don't toggle mongo collection instance variable

---

.github/workflows/ee2-tests.yml
RELEASE_NOTES.md
lib/execution_engine2/sdk/EE2Runjob.py
requirements.txt
scripts/entrypoint.sh
test/tests_for_sdkmr/ee2_load_test.py

* Adds a condor pool token functionality
* Fixes failing flake8 build
* This is currently deployed staging. You can test this by 
```
su kbase
condor_q
condor_status
```
But it is alarming that condor_q is taking 5 seconds. Is something wrong with staging?

DEVOPS-960 Add IDTokens

---

.github/workflows/ee2-tests.yml
RELEASE_NOTES.md
lib/execution_engine2/sdk/EE2Status.py
test/tests_for_sdkmr/EE2Status_test.py

* This was covering up the error that my token was expired!!!
* The catalog was throwing an error like so
```
self = <lib.installed_clients.baseclient.BaseClient object at 0x105798e50>
url = 'https://staging.kbase.us/services/ee2'
method = 'execution_engine2.run_job'
params = [{'app_id': 'simpleapp', 'method': 'simpleapp.simple_add', 'params': [{'base_number': '105'}], 'service_ver': 'dev', ...}]
context = None
def _call(self, url, method, params, context=None):
arg_hash = {
"method": method,
"params": params,
"version": "1.1",
"id": str(_random.random())[2:],
}
if context:
if type(context) is not dict:
raise ValueError("context is not type dict as required.")
arg_hash["context"] = context
body = _json.dumps(arg_hash, cls=_JSONObjectEncoder)
ret = _requests.post(
url,
data=body, …
```

PTV-1832-followup Update catalog call for failed jobs

---

.github/dependabot.yml
.pre-commit-config.yaml
lib/biokbase/log.py
lib/execution_engine2/authclient.py
lib/installed_clients/authclient.py

This PR fix the following:
1. add dependabot.yml in GHA
2. fix pre commit config file
- black code
- fix flake8

add dependabot.yml && fix .pre-commit-config.yaml file

---

.github/dependabot.yml
.github/workflows/check_build.yml
.github/workflows/ee2-tests.yml
.pre-commit-config.yaml
Dockerfile
Makefile
RELEASE_NOTES.md
docker-compose.yml
kbase.yml
lib/biokbase/log.py
lib/execution_engine2/authclient.py
lib/execution_engine2/sdk/EE2Runjob.py
lib/execution_engine2/sdk/job_submission_parameters.py
lib/execution_engine2/utils/application_info.py
lib/execution_engine2/utils/job_requirements_resolver.py
lib/execution_engine2/utils/user_info.py
lib/installed_clients/authclient.py
requirements.txt
test/dockerfiles/mongo/docker-entrypoint-initdb.d-3.6/mongo-init.js
test/dockerfiles/mongo/docker-entrypoint-initdb.d-7.0/mongo-init.js
test/tests_for_auth/ee2_admin_mode_test.py

- Update clients to work with mongo7 by updating pymongo and mongoengine
-  Fix linting issues from flake8 and black
- Update outdated libraries that can no longer be pip installed
- The latest Dockerfile build contains conda which installs python 3.12.4 so these changes will pin python to 3.10 and save us headache in the future
- Speed up tests by moving docker build step out
- Create matrix of tests to run against mongo3.6 and mongo7

D->M 0.0.14

---

RELEASE_NOTES.md
kbase.yml
lib/execution_engine2/execution_engine2Impl.py
scripts/execute_runner.sh

ee2 was changed to send requests and avoid cloudflare, so send them on the internal network
The internal network is not accessible at nersc, so we have to send through cloudflare
These changes/hack modify the job runner to replace that URL when it is running at NERSC to the public URL
These changes are current deployed on production. You can run a hipmer job to prove it and see that they now run.
Corresponding changes in jobRunner are also deployed on production. https://github.com/kbase/JobRunner/pull/87
* Details for how to test the PR:

DEVOPS-2030 Skip Cloudflare at Nersc

---

scripts/execute_runner.sh

* Bugfix, the removal of `services.` should only happen at NERSC, not all KBase Jobs
* See https://github.com/kbase/execution_engine2/pull/489

DEVOPS-2030 Update execute_runner.sh
