kbase/execution_engine2

Makefile, execution_engine2.spec, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/utils/SDKMethodRunner.py, test/ee2_server_test.py, test/test_utils.py
Gonna add more status to this one and tweak the spec file around it.
=> add gitcommit to status, explicit tests on server methods

lib/execution_engine2/db/models/models.py, test/ee2_SDKMethodRunner_test.py
=> Update models.py to add Queued timestamp

lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/authorization/workspaceauth.py, test/ee2_SDKMethodRunner_test.py
also forgot about some stale docstring changes.
fixes #78
=> add global workspace permissions for check_jobs

lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/db/MongoUtil.py, lib/execution_engine2/db/models/models.py, lib/execution_engine2/execution_engine2Impl.py, test/ee2_SDKMethodRunner_test.py, test/test_utils.py
per @eapearson we should use epoch time in milliseconds.
=> Use epoch time

Dockerfile, execution_engine2.spec, lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/execution_engine2Server.py, lib/execution_engine2/utils/Condor.py, scripts/execute_runner.sh, test/ee2_SDKMethodRunner_test.py, test/ee2_catalog_test.py, test/ee2_scheduler_online_test.py
=> check_jobs_date_range_copy

execution_engine2.spec, lib/execution_engine2/execution_engine2Impl.py
update spec to avoid confusion.
=> update spec file

execution_engine2.spec, lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/db/MongoUtil.py, lib/execution_engine2/db/models/models.py, test/ee2_SDKMethodRunner_test.py
See https://github.com/kbase/execution_engine2/issues/71
=> #71 Finished completed

execution_engine2.spec, lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/execution_engine2Impl.py, test/ee2_SDKMethodRunner_test.py
fix issue reported by https://github.com/kbase/execution_engine2/issues/104
=> fix get_job_log ts

execution_engine2.spec, lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/execution_engine2Server.py
addressing https://github.com/kbase/execution_engine2/issues/109
=> remove token from is_admin

lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/execution_engine2Impl.py, test/ee2_SDKMethodRunner_test.py
addressing https://github.com/kbase/execution_engine2/issues/123
=> fix return type error

lib/execution_engine2/db/models/transfer/check_jobs_for_finish_times.py, lib/execution_engine2/db/models/transfer/transfer_ujs_njs.py
=> #81 verify jobs

execution_engine2.spec, lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/execution_engine2Server.py
=> #133 Added endpoint to check admin privs

lib/execution_engine2/db/models/transfer/check_jobs_for_finish_times.py, lib/execution_engine2/db/models/transfer/transfer_logs.py, lib/execution_engine2/db/models/transfer/transfer_ujs_njs.py
=> #81 #138 Changed from 0 to nothing, queued = createdtimestamp

lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/db/MongoUtil.py, lib/execution_engine2/execution_engine2Impl.py, requirements.txt, test/ee2_MongoUtil_test.py, test/ee2_SDKMethodRunner_test.py, test/ee2_load_test.py
* add job_log_exists
* using pymongo to fetch job logs
* remove unused comments
* add more tests
* remove check permission
* fetch job
* reduce thread due to travis time limit
=> add job_log_exists (#153)

deploy.cfg, lib/execution_engine2/utils/Condor.py
* TODO test this with env var in rancher
=> Changed defaults, fixed parameter

execution_engine2.spec, lib/execution_engine2/EE2Logs.py, lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/execution_engine2Server.py, test/ee2_SDKMethodRunner_test.py, test/ee2_server_test.py
add offset and limit to `get_job_logs`
https://github.com/kbase/execution_engine2/issues/108
=> add offset and limit to get_job_logs

Makefile, lib/execution_engine2/EE2Status.py, lib/execution_engine2/db/models/transfer/transfer_ujs_njs.py, lib/execution_engine2/utils/Condor.py, requirements.txt, test/.coveragerc, test/ee2_SDKMethodRunner_ee2_logs.py, test/ee2_SDKMethodRunner_test.py, test/ee2_load_test.py, test/ee2_test_admin_mode.py, test/pytest.ini
Change nose to pytest https://github.com/kbase/execution_engine2/issues/192
=> #192 Pytest2

lib/execution_engine2/EE2Status.py, lib/execution_engine2/db/models/transfer/transfer_ujs_njs.py, lib/execution_engine2/utils/Condor.py, test/ee2_SDKMethodRunner_ee2_logs.py, test/ee2_SDKMethodRunner_test.py, test/ee2_load_test.py, test/ee2_test_admin_mode.py
* Send exec stats and fix sent value to be float 
* UPdate transfer script to keep UJS run time if NJS run time not available
* Fix clientgroup bugs
* Fixing tests and mocking required clients for new call
* Testing out pytest
=> Added catalog stats, fixed cg, fixed ws_objs

deploy.cfg, execution_engine2.spec, lib/execution_engine2/EE2Status.py, lib/execution_engine2/SDKMethodRunner.py, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/execution_engine2Server.py, lib/execution_engine2/utils/CatalogUtils.py, lib/execution_engine2/utils/Condor.py, lib/installed_clients/execution_engine2Client.py, test/deploy.cfg, test/ee2_load_test.py, test/ee2_scheduler_test.py
* Remove separate endpoints and move as_admin into params.
* Need to update narrative and jobrunner clients.
* Updated those clients
* Updated catalog token config for send_exec_stats
=> Revert admin

lib/execution_engine2/db/models/transfer/transfer_logs.py
Make default logs in transfer script have a timestamp of 0, which will be handled by ee2_api.
=> make default log ts to 0

lib/execution_engine2/execution_engine2Impl.py
https://github.com/kbase/execution_engine2/issues/176
=> Srv wiz url was not in config

lib/execution_engine2/db/MongoUtil.py, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/sdk/EE2Authentication.py, lib/execution_engine2/sdk/EE2Runjob.py, lib/execution_engine2/sdk/EE2Status.py, lib/execution_engine2/sdk/EE2StatusRange.py, lib/execution_engine2/sdk/SDKMethodRunner.py, lib/execution_engine2/utils/Condor.py, lib/execution_engine2/utils/EE2Logger.py, lib/execution_engine2/utils/KafkaUtils.py, lib/installed_clients/feeds_client.py, test/ee2_test_admin_mode.py
* Add Logging
* Fix condor job string by adding .0
=> Logging and fix condor_cancel

deploy.cfg, lib/execution_engine2/sdk/EE2Runjob.py, lib/execution_engine2/sdk/EE2Status.py, lib/execution_engine2/sdk/SDKMethodRunner.py, lib/execution_engine2/utils/Condor.py
* Fix permissions on checkjob
* Update request_memory
* Add self.override_clientgroup = os.environ.get("OVERRIDE_CLIENT_GROUP", None)
=> Bugfix check perms

Dockerfile, bin/PurgeHeldJobs.py, codecov.yml, deploy.cfg, execution_engine2.spec, lib/execution_engine2/db/models/models.py, lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/sdk/EE2Runjob.py, lib/execution_engine2/sdk/EE2Status.py, lib/execution_engine2/sdk/EE2StatusRange.py, lib/execution_engine2/utils/Condor.py, lib/execution_engine2/utils/SlackUtils.py, scripts/download_runner.sh, scripts/entrypoint.sh, scripts/execute_runner.sh, test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Runjob_test.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Status_test.py, test/tests_for_sdkmr/ee2_scheduler_test.py
* Add Labels
* Add Refdata env var
=> Added labels, refdata, and stats to checkjobs

RELEASE_NOTES.md, lib/execution_engine2/db/MongoUtil.py, lib/execution_engine2/sdk/EE2Logs.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_EE2Logs_test.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py, test/tests_for_sdkmr/ee2_load_test.py
* Change logs to push instead of update
* Changes logs position offset to 0
=> Change logs to push

lib/execution_engine2/sdk/EE2Status.py
* Fix checkjob error when using a single checkjob call
=> Checkjob error

docs/adrs/rework-batch-analysis-architecture.md
ADR describing our proposed approach for modding the batch analysis architecture. 
N/A for this PR
N/A for this PR
N/A for this PR
=> DATAUP-155 ADR: rework batch analysis architecture

deploy.cfg
Change default cores for njs to 4
=> Make  cores configurable

deploy.cfg
* Update Default Cores
* TODO Set these variables on CI
=> Update Default Cores

Dockerfile
=> Update Dockerfile for quay

lib/execution_engine2/sdk/EE2Status.py, lib/execution_engine2/sdk/EE2StatusRange.py, lib/execution_engine2/sdk/SDKMethodRunner.py, lib/execution_engine2/utils/arg_processing.py, test/tests_for_utils/arg_processing_test.py
Move the boolean parsing function into a separate module. Ran into import cycles when making other changes. Probably makes more sense to have it in a separate module anyway.
- [?] My changes generate no new warnings - too many warnings to realistically check
=> Move boolean parsing to a separate module

lib/execution_engine2/execution_engine2Impl.py, test/tests_for_integration/api_to_db_test.py
Fix is_admin and get_admin_permission bugs and add happy path integration tests for those functions.
- [?] My changes generate no new warnings - over 3k warnings, too hard to check
=> Fix is_admin and get_admin_permission bugs 

lib/execution_engine2/execution_engine2Impl.py, lib/execution_engine2/sdk/EE2Authentication.py, lib/execution_engine2/sdk/EE2Logs.py, lib/execution_engine2/sdk/SDKMethodRunner.py, lib/execution_engine2/utils/CatalogUtils.py, lib/execution_engine2/utils/clients.py, test/tests_for_auth/ee2_admin_mode_test.py, test/tests_for_auth/ee2_authstrategy_test.py, test/tests_for_integration/api_to_db_test.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_EE2Logs_test.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_test.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Runjob_test.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_test_EE2Status_test.py, test/tests_for_sdkmr/ee2_SDKMethodRunner_test_utils.py, test/tests_for_sdkmr/ee2_load_test.py, test/utils_shared/mock_utils.py
Passes in clients via dependency injection.
Allows the clients to be mocked, and therefore makes is easier to unit test
SDKMR without monkey patching.
Also makes it easier to swap out client implementations as long as the new
implementation has the same interface, especially at runtime for alternate
configurations.
- [?] My changes generate no new warnings - over 3k warnings
- [n/a] [Release notes](/RELEASE_NOTES.md) have been updated for each release …
=> Pass in clients via dependency injection

test/tests_for_integration/api_to_db_test.py, unit_testing_guidelines.md
Adds unit testing guidelines. I consider this a rev 0 of a living document and it will undoubtedly be improved in future. IMO it's good enough for a first cut and for other reviewers to look at at this point.
- [n/a] Tests pass in Github Actions and locally 
- [n/a] Changes available by spinning up a local test suite and doing X
- [n/a] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [n/a] My changes generate no new warnings
- [n/a] New and existing unit tests pass …
=> Add unit testing guidelines

test/utils_shared/mock_utils.py
Refactor repetitive code in the mock helper module as per https://github.com/kbase/execution_engine2/pull/320#pullrequestreview-601107047
- [?] My changes generate no new warnings - over 3k
=> DRY up mock_utils.py

lib/execution_engine2/utils/arg_processing.py, test/tests_for_utils/arg_processing_test.py
Adds argument / parameter checking helper code for use in future PRs.
- [?] My changes generate no new warnings - over 3k warnings
=> Add argument / parameter checkers

lib/execution_engine2/utils/arg_processing.py, lib/execution_engine2/utils/user_info.py, test/tests_for_utils/user_info_test.py
Might add more fields later as needed, but there's a couple places where this info
is showing up so a container makes sense. Will integrate it in later PRs
- [?] My changes generate no new warnings - over 3K 
=> Add user info class to hold user information 

lib/execution_engine2/utils/application_info.py, test/tests_for_utils/application_info_test.py
Will be part of a job reqs class in the future
=> DATAUP-389 Add application info class

lib/execution_engine2/sdk/job_submission_parameters.py, test/tests_for_sdkmr/job_submission_parameters_test.py
Contains all the information necessary to run a job on Condor.
=> DATAUP-389 Add job submission parameters class

test/tests_for_integration/api_to_db_test.py
Factor out helper methods from the run_job integration test for reuse in future tests. Doing it now to make future PRs easier to read.
=> DATAUP-389 - Factor out helper methods for run_job integration test

lib/execution_engine2/db/MongoUtil.py, lib/execution_engine2/sdk/EE2Runjob.py, lib/execution_engine2/utils/Condor.py
=> DATAUP-423 Removed extra logging

lib/execution_engine2/utils/Condor.py, lib/execution_engine2/utils/job_requirements_resolver.py, test/tests_for_utils/job_requirements_resolver_test.py
Needs to check for `TypeError` as well as `ValueError` in case something other than a string / int / float is passed in.
Also remove a couple of unused imports.
=> DATAUP-389 - Fix bug in job requirements resolver

lib/execution_engine2/sdk/EE2Runjob.py
* Please include a summary of the change and which issue is fixed. 
* Please also include relevant motivation and context.
* List any dependencies that are required for this change.
* Details for how to test the PR:
=> Testing job times

lib/execution_engine2/db/models/models.py
Reverts kbase/execution_engine2#389
=> Revert "Update models.py"

lib/execution_engine2/sdk/EE2Status.py
Error while trying to start your app (run_app_bulk)!
-----------------------------------------------------
Unable to fetch info for job 60d6205d09b619fd9d292ad6 - Server error: -32000. "'NoneType' object has no attribute 'parent_job_id'"
Traceback (most recent call last):
File "/kb/module/lib/execution_engine2/execution_engine2Server.py", line 101, in _call_method
result = method(ctx, *params)
File "/kb/module/lib/execution_engine2/execution_engine2Impl.py", line 1011, in check_job
job_state = mr.check_job(
File "/kb/module/lib/execution_engine2/sdk/SDKMethodRunner.py", line 418, in check_job
return self.get_jobs_status().check_job(
File "/kb/module/lib/execution_engine2/sdk/EE2Status.py", line 419, in check_job
job_state = self.check_jobs(
File …
=> Fix parent job id

lib/execution_engine2/execution_engine2Impl.py, test/tests_for_integration/api_to_db_test.py, test/tests_for_sdkmr/ee2_load_test.py, test/utils_shared/test_utils.py
* Parameter got renamed. That means we missed the impl tests for this function.
=> check_job_batch_bugaroo

Dockerfile
* Removes JARS from built image.
=> Removed jars from build
